#include <vvr/palette.h>

//! LEGACY PALETTE BY ME
const vvr::Colour vvr::red(0xFF, 0x00, 0x00);
const vvr::Colour vvr::blue(0x00, 0x00, 0xFF);
const vvr::Colour vvr::grey(0x66, 0x66, 0x66);
const vvr::Colour vvr::cyan(0x00, 0xFF, 0xFF);
const vvr::Colour vvr::white(0xFF, 0xFF, 0xFF);
const vvr::Colour vvr::green(0x00, 0xFF, 0x00);
const vvr::Colour vvr::black(0x00, 0x00, 0x00);
const vvr::Colour vvr::yellow(0xFF, 0xFF, 0x00);
const vvr::Colour vvr::orange(0xFF, 0x66, 0x00);
const vvr::Colour vvr::magenta(0xFF, 0x00, 0xFF);
const vvr::Colour vvr::darkRed(0x8B, 0x00, 0x00);
const vvr::Colour vvr::darkOrange(0xFF, 0x8C, 0x00);
const vvr::Colour vvr::darkGreen(0x00, 0x64, 0x00);
const vvr::Colour vvr::yellowGreen(0x9A, 0xCD, 0x32);
const vvr::Colour vvr::lilac(0xCD, 0xA9, 0xCD);

//! PALETTE FOUND ONLINE
const vvr::Colour vvr::AliceBlue(0xF0F8FF);
const vvr::Colour vvr::AntiqueWhite(0xFAEBD7);
const vvr::Colour vvr::Aqua(0x00FFFF);
const vvr::Colour vvr::Aquamarine(0x7FFFD4);
const vvr::Colour vvr::Azure(0xF0FFFF);
const vvr::Colour vvr::Beige(0xF5F5DC);
const vvr::Colour vvr::Bisque(0xFFE4C4);
const vvr::Colour vvr::Black(0x000000);
const vvr::Colour vvr::BlanchedAlmond(0xFFEBCD);
const vvr::Colour vvr::Blue(0x0000FF);
const vvr::Colour vvr::BlueViolet(0x8A2BE2);
const vvr::Colour vvr::Brown(0xA52A2A);
const vvr::Colour vvr::BurlyWood(0xDEB887);
const vvr::Colour vvr::CadetBlue(0x5F9EA0);
const vvr::Colour vvr::Chartreuse(0x7FFF00);
const vvr::Colour vvr::Chocolate(0xD2691E);
const vvr::Colour vvr::Coral(0xFF7F50);
const vvr::Colour vvr::CornflowerBlue(0x6495ED);
const vvr::Colour vvr::Cornsilk(0xFFF8DC);
const vvr::Colour vvr::Crimson(0xDC143C);
const vvr::Colour vvr::Cyan(0x00FFFF);
const vvr::Colour vvr::DarkBlue(0x00008B);
const vvr::Colour vvr::DarkCyan(0x008B8B);
const vvr::Colour vvr::DarkGoldenrod(0xB8860B);
const vvr::Colour vvr::DarkGray(0xA9A9A9);
const vvr::Colour vvr::DarkGreen(0x006400);
const vvr::Colour vvr::DarkKhaki(0xBDB76B);
const vvr::Colour vvr::DarkMagenta(0x8B008B);
const vvr::Colour vvr::DarkOliveGreen(0x556B2F);
const vvr::Colour vvr::DarkOrange(0xFF8C00);
const vvr::Colour vvr::DarkOrchid(0x9932CC);
const vvr::Colour vvr::DarkRed(0x8B0000);
const vvr::Colour vvr::DarkSalmon(0xE9967A);
const vvr::Colour vvr::DarkSeaGreen(0x8FBC8F);
const vvr::Colour vvr::DarkSlateBlue(0x483D8B);
const vvr::Colour vvr::DarkSlateGray(0x2F4F4F);
const vvr::Colour vvr::DarkTurquoise(0x00CED1);
const vvr::Colour vvr::DarkViolet(0x9400D3);
const vvr::Colour vvr::DeepPink(0xFF1493);
const vvr::Colour vvr::DeepSkyBlue(0x00BFFF);
const vvr::Colour vvr::DimGray(0x696969);
const vvr::Colour vvr::DodgerBlue(0x1E90FF);
const vvr::Colour vvr::FireBrick(0xB22222);
const vvr::Colour vvr::FloralWhite(0xFFFAF0);
const vvr::Colour vvr::ForestGreen(0x228B22);
const vvr::Colour vvr::Fuchsia(0xFF00FF);
const vvr::Colour vvr::Gainsboro(0xDCDCDC);
const vvr::Colour vvr::GhostWhite(0xF8F8FF);
const vvr::Colour vvr::Gold(0xFFD700);
const vvr::Colour vvr::Goldenrod(0xDAA520);
const vvr::Colour vvr::Gray(0x808080);
const vvr::Colour vvr::Green(0x008000);
const vvr::Colour vvr::GreenYellow(0xADFF2F);
const vvr::Colour vvr::Honeydew(0xF0FFF0);
const vvr::Colour vvr::HotPink(0xFF69B4);
const vvr::Colour vvr::IndianRed(0xCD5C5C);
const vvr::Colour vvr::Indigo(0x4B0082);
const vvr::Colour vvr::Ivory(0xFFFFF0);
const vvr::Colour vvr::Khaki(0xF0E68C);
const vvr::Colour vvr::Lavender(0xE6E6FA);
const vvr::Colour vvr::LavenderBlush(0xFFF0F5);
const vvr::Colour vvr::LawnGreen(0x7CFC00);
const vvr::Colour vvr::LemonChiffon(0xFFFACD);
const vvr::Colour vvr::LightBlue(0xADD8E6);
const vvr::Colour vvr::LightCoral(0xF08080);
const vvr::Colour vvr::LightCyan(0xE0FFFF);
const vvr::Colour vvr::LightGoldenrodYellow(0xFAFAD2);
const vvr::Colour vvr::LightGreen(0x90EE90);
const vvr::Colour vvr::LightGrey(0xD3D3D3);
const vvr::Colour vvr::LightPink(0xFFB6C1);
const vvr::Colour vvr::LightSalmon(0xFFA07A);
const vvr::Colour vvr::LightSeaGreen(0x20B2AA);
const vvr::Colour vvr::LightSkyBlue(0x87CEFA);
const vvr::Colour vvr::LightSlateGray(0x778899);
const vvr::Colour vvr::LightSteelBlue(0xB0C4DE);
const vvr::Colour vvr::LightYellow(0xFFFFE0);
const vvr::Colour vvr::Lime(0x00FF00);
const vvr::Colour vvr::LimeGreen(0x32CD32);
const vvr::Colour vvr::Linen(0xFAF0E6);
const vvr::Colour vvr::Magenta(0xFF00FF);
const vvr::Colour vvr::Maroon(0x800000);
const vvr::Colour vvr::MediumAquamarine(0x66CDAA);
const vvr::Colour vvr::MediumBlue(0x0000CD);
const vvr::Colour vvr::MediumOrchid(0xBA55D3);
const vvr::Colour vvr::MediumPurple(0x9370DB);
const vvr::Colour vvr::MediumSeaGreen(0x3CB371);
const vvr::Colour vvr::MediumSlateBlue(0x7B68EE);
const vvr::Colour vvr::MediumSpringGreen(0x00FA9A);
const vvr::Colour vvr::MediumTurquoise(0x48D1CC);
const vvr::Colour vvr::MediumVioletRed(0xC71585);
const vvr::Colour vvr::MidnightBlue(0x191970);
const vvr::Colour vvr::MintCream(0xF5FFFA);
const vvr::Colour vvr::MistyRose(0xFFE4E1);
const vvr::Colour vvr::Moccasin(0xFFE4B5);
const vvr::Colour vvr::NavajoWhite(0xFFDEAD);
const vvr::Colour vvr::Navy(0x000080);
const vvr::Colour vvr::OldLace(0xFDF5E6);
const vvr::Colour vvr::Olive(0x808000);
const vvr::Colour vvr::OliveDrab(0x6B8E23);
const vvr::Colour vvr::Orange(0xFFA500);
const vvr::Colour vvr::OrangeRed(0xFF4500);
const vvr::Colour vvr::Orchid(0xDA70D6);
const vvr::Colour vvr::PaleGoldenrod(0xEEE8AA);
const vvr::Colour vvr::PaleGreen(0x98FB98);
const vvr::Colour vvr::PaleTurquoise(0xAFEEEE);
const vvr::Colour vvr::PaleVioletRed(0xDB7093);
const vvr::Colour vvr::PapayaWhip(0xFFEFD5);
const vvr::Colour vvr::PeachPuff(0xFFDAB9);
const vvr::Colour vvr::Peru(0xCD853F);
const vvr::Colour vvr::Pink(0xFFC0CB);
const vvr::Colour vvr::Plum(0xDDA0DD);
const vvr::Colour vvr::PowderBlue(0xB0E0E6);
const vvr::Colour vvr::Purple(0x800080);
const vvr::Colour vvr::Red(0xFF0000);
const vvr::Colour vvr::RosyBrown(0xBC8F8F);
const vvr::Colour vvr::RoyalBlue(0x4169E1);
const vvr::Colour vvr::SaddleBrown(0x8B4513);
const vvr::Colour vvr::Salmon(0xFA8072);
const vvr::Colour vvr::SandyBrown(0xF4A460);
const vvr::Colour vvr::SeaGreen(0x2E8B57);
const vvr::Colour vvr::Seashell(0xFFF5EE);
const vvr::Colour vvr::Sienna(0xA0522D);
const vvr::Colour vvr::Silver(0xC0C0C0);
const vvr::Colour vvr::SkyBlue(0x87CEEB);
const vvr::Colour vvr::SlateBlue(0x6A5ACD);
const vvr::Colour vvr::SlateGray(0x708090);
const vvr::Colour vvr::Snow(0xFFFAFA);
const vvr::Colour vvr::SpringGreen(0x00FF7F);
const vvr::Colour vvr::SteelBlue(0x4682B4);
const vvr::Colour vvr::Tan(0xD2B48C);
const vvr::Colour vvr::Teal(0x008080);
const vvr::Colour vvr::Thistle(0xD8BFD8);
const vvr::Colour vvr::Tomato(0xFF6347);
const vvr::Colour vvr::Turquoise(0x40E0D0);
const vvr::Colour vvr::Violet(0xEE82EE);
const vvr::Colour vvr::Wheat(0xF5DEB3);
const vvr::Colour vvr::White(0xFFFFFF);
const vvr::Colour vvr::WhiteSmoke(0xF5F5F5);
const vvr::Colour vvr::Yellow(0xFFFF00);
const vvr::Colour vvr::YellowGreen(0x9ACD32);
